name: GitHub Actions CI

on:
  push:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  buildx:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - 2.7
          - 3.7
          - 3.8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker container
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          curl -fsSL https://raw.githubusercontent.com/pschmitt/ci-setup-docker-buildx/master/setup.sh | bash
          ./build.sh ${{ matrix.python_version }} -p
